version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    command: bash -c "rm -rf tmp/pids && bin/rails server -p 3000 -b 0.0.0.0"
    volumes:
      - .:/money-monitor
      - /money-monitor/.bundle
      - bundle-cache:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    extra_hosts:
      - "dockerhost:172.17.0.1"
  db:
    extends:
      file: docker/db-template.yml
      service: db
    volumes: [db_data:/var/lib/postgresql/data]
    ports: 
      - "5432:5432"
volumes:
  db_data:
  bundle-cache:
