version: "3.9"

services:
  db:
    image: postgres:15
    user: postgres
    environment:
      POSTGRES_PASSWORD: password
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    ports:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 3s
      timeout: 6s
      retries: 5
